@Test public void should_fail_since_actual_is_not_one(){
  assertThatExceptionOfType(AssertionError.class).isThrownBy(() -> integers.assertIsOne(someInfo(),0)).withMessage(format("%nExpecting:%n <0>%nto be equal to:%n <1>%nbut was not."));
}
