@Test public void allSatisfy_interruptedException(){
  Thread.currentThread().interrupt();
  Verify.assertThrowsWithCause(RuntimeException.class,InterruptedException.class,() -> this.classUnderTest().allSatisfy(new CheckedPredicate<Integer>(){
    @Override public boolean safeAccept(    Integer each) throws InterruptedException {
      Thread.sleep(1000);
      throw new AssertionError();
    }
  }
));
  Assert.assertTrue(Thread.interrupted());
  Assert.assertFalse(Thread.interrupted());
}
