@Test public void should_fail_if_completable_future_is_completed(){
  CompletableFuture<String> future=CompletableFuture.completedFuture("done");
  assertThatThrownBy(() -> assertThat(future).hasFailedWithThrowableThat()).isInstanceOf(AssertionError.class).hasMessage(shouldHaveFailed(future).create());
}
