@Test public void shouldThrowErrorWithGivenMessageAndCause(){
  String message="Some Throwable";
  Throwable cause=new Throwable();
  assertThatExceptionOfType(AssertionError.class).isThrownBy(() -> Fail.fail(message,cause)).withMessage(message).withCause(cause);
}
