@Test public void should_throw_error_wrapping_catched_IOException() throws IOException {
  IOException cause=new IOException();
  when(diff.diff(actual,defaultCharset(),other,defaultCharset())).thenThrow(cause);
  when(nioFilesWrapper.exists(actual)).thenReturn(true);
  when(nioFilesWrapper.isReadable(actual)).thenReturn(true);
  when(nioFilesWrapper.isReadable(other)).thenReturn(true);
  assertThatExceptionOfType(UncheckedIOException.class).isThrownBy(() -> paths.assertHasSameContentAs(someInfo(),actual,defaultCharset(),other,defaultCharset())).withCause(cause);
}
